[project]
name = "optimization-instance-hub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs-material>=9.6.20",
    "mkdocs>=1.6.1",
    "mkdocs-gen-files>=0.5.0",
]
