site_name: Optimization Instance Hub
theme:
  name: material
  palette:
    primary: pink
  language: ja

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - attr_list

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/generate_index_page.py

watch:
  - ../incetances
